version: '3.8'
services:
  app:
    build: .
    ports:
      - "8088:8088"
    depends_on:
      - db
    environment:
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: articles-postgres-db
      POSTGRES_USER: ssanchez
      POSTGRES_PASSWORD: chall3ng3!
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres-data: