spring:
  security:
    secret-key: ZNH2hWnwZ0HyAk3gEy7ZcgxnyzBBKQqgQcrFVx/MKug=
    user:
      name: challenge-username
      password: challenge-password
  application:
    name: challenge
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://db:5432/articles-postgres-db
    username: ssanchez
    password: chall3ng3!
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
server:
  port: 8088
logging:
  level:
    ROOT: INFO
    com.challenge: DEBUG
  file:
    name: challenge-application.log
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'
